### ISSUE TITLE
How to uninstall the desktoppr if the '.pkg' was used to install it?

### ISSUE THREAD

**Issue by EugeneTarasenko** [scriptingosx/desktoppr#21]

**Comment by scriptingosx** [comment]
Same as any other pkg. You inspect the pkg to see what files it installs and remove those. You can use tools such as [Suspicious Package](https://www.mothersruin.com/software/SuspiciousPackage/) for that. You can also run `pkgutil` on a Mac that has the desktoppr.pkg installed:

```
> pkgutil --files com.scriptingosx.desktoppr 
usr
usr/local
usr/local/bin
usr/local/bin/desktoppr
```

Here you can see that the desktoppr pkg only install a single binary file in `/usr/local/bin`. So, to uninstall, all you have to do is

```
rm /usr/local/bin/desktoppr
```

Then, you should also tell the system that this software was ever installed, otherwise re-installing the pkg in the future might not work as expected:

```
pkgutil --forget com.scriptingosx.desktoppr
```
