### ISSUE TITLE
Return which image has been randomly picked from the specified folder

### ISSUE THREAD

**Issue by jtrott** [scriptingosx/desktoppr#9]
I don't know if an API is even available, but I would like to know which random image from the folder is currently loaded on the desktop, not the folder from which it has been selected.

**Comment by scriptingosx** [comment]
you can get this information with AppleScript/osascript:

```
osascript -e 'tell application "Finder" to get POSIX path of (desktop picture as alias)'
```

But this will require Terminal/your script/whatever is executing this to be allowed to send Apple events to Finder in the Privacy preference pane. Since the entire point of desktoppr is to _avoid_ such permissions, I will not add this to the desktoppr binary itself.

But you can of course use the above.

**Comment by jtrott** [comment]
That may work when you have only a single internal monitor (still gives me the wrong result here on Catalina), that does not work when you have more than 1 monitor.
